from __future__ import annotations


BARCLEAN_RAW_AXIAL_REFERENCE_M = 0.22606532
BARCLEAN_OBSTACLE_NEAR_ENDPOINT_AXIAL_M = -0.15
BARCLEAN_AXIAL_DISPLAY_SHIFT_M = (
    BARCLEAN_RAW_AXIAL_REFERENCE_M - BARCLEAN_OBSTACLE_NEAR_ENDPOINT_AXIAL_M
)
