<?xml version="1.0"?>
<package format="2">
  <name>stage_real_executor</name>
  <version>0.1.0</version>
  <description>Validated Cartesian Path to iiwa14 joint trajectory executor.</description>
  <maintainer email="baiyu@example.com">Baiyu</maintainer>
  <license>Proprietary</license>

  <buildtool_depend>catkin</buildtool_depend>
  <depend>actionlib</depend>
  <depend>actionlib_msgs</depend>
  <depend>control_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>iiwa_description</depend>
  <depend>iiwa_driver</depend>
  <depend>nav_msgs</depend>
  <depend>rospy</depend>
  <depend>sensor_msgs</depend>
  <depend>stage_cartesian_trajectory</depend>
  <depend>stage_constraint_planner</depend>
  <depend>std_msgs</depend>
  <depend>std_srvs</depend>
  <depend>trajectory_msgs</depend>
  <exec_depend>python3-rospkg</exec_depend>
</package>
